---
title: "Data Import"
author: "Xue Yang"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## Import FAS csv files

Import my first csv.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
# use this kind of a relative path to the same file can help when move the file
# getwd() to know where the file is 
# ?read_csv to know something about read_csv

litters_data = janitor::clean_names(litters_data) 
# use janitor::clean_names() to clean up variable names after importing data. Doing so will take whatever the column names are and convert them to lower snake case.

# janitor is a package and clean_names is the function in the package, the advantage of use this to make sure if there are some funtion with the same name and make some conflict
```

Import the pups also

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")  
```


## Look at the data

Look at litters data.

```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)

# View(litters_data) can not wirte in the Rmd, but it realy works
```


Skip some rows; omit variable names.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

```{r}
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
skimr::skim(pups_data)
```


Take a look at pups!

```{r}
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)
```


## Other formats

Read in mlb data

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")
# ?read::read_excel
mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
```



Read in pluse data:

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```


## Compare with base R

```{r}
pups_readr = read_csv("./data/FAS_pups.csv")  #tibble
pups_baser = read.csv("./data/FAS_pups.csv")  #data frame
```

