---
title: "Tidy data"
author: "Xue Yang"
date: "9/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)   # collection of some package which make things more easily
```


## gather

PULSE data

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
# pulse_data %>% View
```

This isn't tidy yet ...

```{r}
# ?gather
pulse_tidy = pulse_data %>% 
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m) 
# pulse_tidy %>% View("tidy")
# pulse_tidy %>% View("nontidy")
```

Illustrate 'separate'

```{r}
# ?separate
pulse_tidy %>% 
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>% 
  select(-bdi_str, -score_str)%>% 
  mutate(visit = replace(visit, visit == "bl", "00m"))
```


All togther, the data import/ cleaning pipeline is:

```{r}
pluse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m) %>% 
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>% 
  select(-bdi_str, -score_str) %>% 
  mutate(visit = replace(visit, visit == "bl", "00m"))
```


## Revisit FAS_litters

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day"), 3) %>% 
  # 3 means separate by the 3rd words
  mutate(dose = tolower(dose),
         wt_gain = gd18_weight - gd0_weight) %>%
  arrange(litter_number)

litters_data
```


Data cleaning/tidying

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>% 
  select(litter_number, ends_with("weight")) %>% 
  gather(key = "gest_day", value = "weight", gd0_weight:gd18_weight) %>%
  mutate(gest_day = recode(gest_day, "gd0_weight" = 0, "gd18_weight" = 18)) %>% 
  arrange(litter_number)
```


## Spread

Create 'analysis_result'

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
# it is tidy but not readable

```

Make it readable:
 
```{r}
analysis_result %>% 
  spread(key = time, value = mean) %>% 
  knitr::kable()
```

## Binding rows

Read in LotR data:
```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

Creat final LotR data to stick them together

```{r}
bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  gather(key = sex, value = word, female:male) %>% 
  mutate(race = tolower(race))
```

## Join data

load the FAS

```{r}
pup_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))

# View(pup_data)
# View(litter_data)

```



Create joined data

```{r}
# not do any left_join or right_join after the pipes because pipes means to do things follow the last one, but join means to take two seperate thing together.

fas_data = left_join(pup_data, litter_data, by = "litter_number")
```



